fix: added output example

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,25 +1,28 @@
-# Store this file in .git/hooks/
 #!/bin/bash
 
-# Get a list of staged Terraform files
-terraform_files=$(git diff --cached --name-only --diff-filter=AM | grep '\.tf$')
+# Navigate to the repository root
+repo_root=$(git rev-parse --show-toplevel)
+cd "$repo_root" || exit 1
+
+# Find all Terraform files in aws, azure, and kubernetes directories
+terraform_files=$(find aws azure kubernetes -type f -name "*.tf")
 
 if [[ -z "$terraform_files" ]]; then
     exit 0
 fi
 
-# Run terraform fmt and check for changes
-formatted_files=()
+# Check formatting of each Terraform file
+failed=()
 for file in $terraform_files; do
-    terraform fmt -diff -write=false "$file"
-    if ! git diff --exit-code "$file" > /dev/null; then
-        formatted_files+=("$file")
+    if ! terraform fmt -check "$file"; then
+        failed+=("$file")
     fi
 done
 
-if [[ ${#formatted_files[@]} -ne 0 ]]; then
+# If there are unformatted files, notify the user and exit with an error
+if [[ ${#failed[@]} -ne 0 ]]; then
     echo "The following Terraform files are not formatted correctly:"
-    for file in "${formatted_files[@]}"; do
+    for file in "${failed[@]}"; do
         echo " - $file"
     done
     echo "Run 'terraform fmt' to fix formatting."
